int controller_loadFromText(char* path , LinkedList* pArrayListCliente);
int controller_loadFromBinary(char* path , LinkedList* pArrayListCliente);
int controller_addCliente(LinkedList* pArrayListCliente);
int controller_editCliente(LinkedList* pArrayListCliente);
int controller_removeCliente(LinkedList* pArrayListCliente);
int controller_ListCliente(LinkedList* pArrayListCliente);
int controller_sortCliente(LinkedList* pArrayListCliente);
int controller_saveAsText(char* path , LinkedList* pArrayListCliente);
int controller_saveAsBinary(char* path , LinkedList* pArrayListCliente);
int controller_nextId(LinkedList* pArrayListCliente);
void Controller_printMenu();
void Controller_filtrarPorValorFloat(LinkedList *pArrayListCliente);
void Controller_filtrarPorHoras(LinkedList *pArrayListCliente);
